/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 21:50:55 GMT 2020
 */

package org.apache.tools.ant.taskdefs.compilers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.Javac;
import org.apache.tools.ant.taskdefs.compilers.Gcj;
import org.apache.tools.ant.taskdefs.compilers.Javac13;
import org.apache.tools.ant.taskdefs.compilers.JavacExternal;
import org.apache.tools.ant.taskdefs.compilers.Jikes;
import org.apache.tools.ant.taskdefs.compilers.Jvc;
import org.apache.tools.ant.taskdefs.compilers.Kjc;
import org.apache.tools.ant.taskdefs.compilers.Sj;
import org.apache.tools.ant.types.Commandline;
import org.apache.tools.ant.types.Path;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DefaultCompilerAdapter_ESTest extends DefaultCompilerAdapter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Jvc jvc0 = new Jvc();
      Javac javac0 = jvc0.getJavac();
      assertNull(javac0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Sj sj0 = new Sj();
      // Undeclared exception!
      try { 
        sj0.setupModernJavacCommandlineSwitches((Commandline) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Jvc jvc0 = new Jvc();
      // Undeclared exception!
      try { 
        jvc0.setupModernJavacCommand();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Jikes jikes0 = new Jikes();
      // Undeclared exception!
      try { 
        jikes0.setupJavacCommandlineSwitches((Commandline) null, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      JavacExternal javacExternal0 = new JavacExternal();
      // Undeclared exception!
      try { 
        javacExternal0.setupJavacCommandlineSwitches((Commandline) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Kjc kjc0 = new Kjc();
      // Undeclared exception!
      try { 
        kjc0.setupJavacCommand(true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Gcj gcj0 = new Gcj();
      // Undeclared exception!
      try { 
        gcj0.setupJavacCommand();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Kjc kjc0 = new Kjc();
      // Undeclared exception!
      try { 
        kjc0.setJavac((Javac) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Javac13 javac13_0 = new Javac13();
      // Undeclared exception!
      try { 
        javac13_0.logAndAddFilesToCompile((Commandline) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Gcj gcj0 = new Gcj();
      String[] stringArray0 = new String[9];
      stringArray0[0] = "/~^hBd=&O':.PN\"t[e{";
      // Undeclared exception!
      try { 
        gcj0.executeExternalCompile(stringArray0, 1);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Can't handle single and double quotes in same argument
         //
         verifyException("org.apache.tools.ant.types.Commandline", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Gcj gcj0 = new Gcj();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        gcj0.executeExternalCompile(stringArray0, 2106);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Jikes jikes0 = new Jikes();
      // Undeclared exception!
      try { 
        jikes0.assumeJava13();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Jikes jikes0 = new Jikes();
      // Undeclared exception!
      try { 
        jikes0.assumeJava12();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Sj sj0 = new Sj();
      // Undeclared exception!
      try { 
        sj0.assumeJava11();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Sj sj0 = new Sj();
      Path path0 = sj0.getCompileClasspath();
      // Undeclared exception!
      try { 
        sj0.addExtdirsToClasspath(path0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.Path", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Kjc kjc0 = new Kjc();
      // Undeclared exception!
      try { 
        kjc0.addCurrentCompilerArgs((Commandline) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.DefaultCompilerAdapter", e);
      }
  }
}
