/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:59:20 GMT 2020
 */

package org.apache.tools.ant.taskdefs.compilers;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.compilers.JavacExternal;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JavacExternal_ESTest extends JavacExternal_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JavacExternal javacExternal0 = new JavacExternal();
      // Undeclared exception!
      try { 
        javacExternal0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.compilers.JavacExternal", e);
      }
  }
}
