/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 21:53:48 GMT 2020
 */

package org.apache.tools.ant.taskdefs.email;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.Location;
import org.apache.tools.ant.Project;
import org.apache.tools.ant.RuntimeConfigurable;
import org.apache.tools.ant.Target;
import org.apache.tools.ant.taskdefs.email.EmailAddress;
import org.apache.tools.ant.taskdefs.email.EmailTask;
import org.apache.tools.ant.taskdefs.email.Message;
import org.apache.tools.ant.types.FileSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EmailTask_ESTest extends EmailTask_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      RuntimeConfigurable runtimeConfigurable0 = emailTask0.getRuntimeConfigurableWrapper();
      emailTask0.setRuntimeConfigurableWrapper(runtimeConfigurable0);
      String string0 = "";
      emailTask0.setMessage("");
      emailTask0.setSubject("");
      emailTask0.getProject();
      String string1 = "/c#f?l<L\"u0P5!'s]";
      emailTask0.setSubject("/c#f?l<L\"u0P5!'s]");
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        emailTask0.setMessageFile(file0);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Only one message can be sent in an email
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.getDescription();
      emailTask0.setMailport(1);
      emailTask0.setMailport(1);
      emailTask0.setMailhost("3");
      emailTask0.setFrom("3");
      EmailTask.Encoding emailTask_Encoding0 = new EmailTask.Encoding();
      emailTask_Encoding0.toString();
      emailTask0.setMessageMimeType("C3PVynfXTMBfD7,YBP");
      emailTask_Encoding0.toString();
      emailTask0.setEncoding(emailTask_Encoding0);
      emailTask0.setFailOnError(true);
      emailTask_Encoding0.getValues();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      emailTask_Encoding0.getValues();
      emailTask0.setMessageFile(file0);
      emailTask0.setFailOnError(true);
      emailTask0.setBccList("3");
      emailTask_Encoding0.getValues();
      emailTask0.setIncludefilenames(true);
      emailTask0.setBccList("3");
      // Undeclared exception!
      try { 
        emailTask0.setFrom("~}");
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Emails can only be from one address
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.getRuntimeConfigurableWrapper();
      emailTask0.setIncludefilenames(true);
      // Undeclared exception!
      try { 
        emailTask0.setCcList((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.StringTokenizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      EmailTask.Encoding emailTask_Encoding0 = new EmailTask.Encoding();
      emailTask_Encoding0.getIndex();
      String[] stringArray0 = emailTask_Encoding0.getValues();
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      EmailAddress emailAddress0 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.addCc(emailAddress0);
      EmailAddress emailAddress1 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.setCcList("");
      emailTask0.setSubject("l3'o<5MYKXkB{*sd`");
      emailTask0.addTo(emailAddress1);
      EmailAddress emailAddress2 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.addBcc(emailAddress2);
      String string0 = "";
      emailTask0.setMessage("");
      int int0 = 0;
      emailTask0.init();
      // Undeclared exception!
      try { 
        emailTask0.setMessage("");
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Only one message can be sent in an email
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      EmailTask.Encoding emailTask_Encoding0 = new EmailTask.Encoding();
      EmailTask emailTask0 = new EmailTask();
      EmailAddress emailAddress0 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.addBcc(emailAddress0);
      emailTask0.getRuntimeConfigurableWrapper();
      emailTask0.setTaskType("Gpidne`");
      boolean boolean0 = false;
      emailTask0.setFailOnError(false);
      EmailAddress emailAddress1 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.addTo(emailAddress1);
      EmailAddress emailAddress2 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.addBcc(emailAddress2);
      EmailAddress emailAddress3 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.addFrom(emailAddress3);
      emailTask0.setDescription("c");
      emailTask0.setMailport(0);
      emailTask0.setFiles("");
      EmailAddress emailAddress4 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.setMessageMimeType("x9kPrwb<hFM2");
      emailTask0.addTo((EmailAddress) null);
      // Undeclared exception!
      try { 
        emailTask0.addFrom(emailAddress4);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Emails can only be from one address
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.reconfigure();
      String string0 = null;
      // Undeclared exception!
      try { 
        emailTask0.setToList((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.StringTokenizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.addMessage((Message) null);
      String string0 = "_Jl&2\\?}|Ne3'$";
      emailTask0.setToList("_Jl&2?}|Ne3'$");
      emailTask0.setMailhost("_Jl&2?}|Ne3'$");
      emailTask0.setMailport((-186));
      String string1 = null;
      // Undeclared exception!
      try { 
        emailTask0.setBccList((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.StringTokenizer", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.setMailport((-3067));
      Message message0 = null;
      emailTask0.addMessage((Message) null);
      emailTask0.setMailport(0);
      emailTask0.getIncludeFileNames();
      emailTask0.getRuntimeConfigurableWrapper();
      // Undeclared exception!
      try { 
        emailTask0.setEncoding((EmailTask.Encoding) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      String string0 = "";
      emailTask0.setSubject("");
      Location location0 = emailTask0.getLocation();
      emailTask0.setLocation(location0);
      emailTask0.setMailhost("");
      String string1 = "z:S (XZm:</&;";
      emailTask0.setBccList("");
      // Undeclared exception!
      try { 
        emailTask0.setFiles("z:S (XZm:</&;");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.getProject();
      EmailTask.Encoding emailTask_Encoding0 = new EmailTask.Encoding();
      emailTask0.setEncoding(emailTask_Encoding0);
      emailTask0.setProject((Project) null);
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      emailTask0.setMessageFile(file0);
      emailTask0.reconfigure();
      emailTask0.init();
      FileSet fileSet0 = mock(FileSet.class, new ViolatedAssumptionAnswer());
      emailTask0.addFileset(fileSet0);
      RuntimeConfigurable runtimeConfigurable0 = emailTask0.getRuntimeConfigurableWrapper();
      emailTask0.setRuntimeConfigurableWrapper(runtimeConfigurable0);
      // Undeclared exception!
      try { 
        emailTask0.setFiles("vmEa}F");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.setToList("");
      String string0 = null;
      emailTask0.getIncludeFileNames();
      // Undeclared exception!
      try { 
        emailTask0.log("_sAK: ycO", 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.setLocation((Location) null);
      emailTask0.setMessage("g7)<");
      emailTask0.setSubject("");
      Message message0 = mock(Message.class, new ViolatedAssumptionAnswer());
      emailTask0.getOwningTarget();
      try { 
        emailTask0.addMessage(message0);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Only one message can be sent in an email
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      // Undeclared exception!
      try { 
        emailTask0.setFiles(")il%<{%YBO\"9H");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.email.EmailTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      emailTask0.getProject();
      emailTask0.setProject((Project) null);
      EmailAddress emailAddress0 = mock(EmailAddress.class, new ViolatedAssumptionAnswer());
      emailTask0.addFrom(emailAddress0);
      emailTask0.setMessageMimeType((String) null);
      emailTask0.setMailport(699);
      emailTask0.setSubject("wFqL]v;0B");
      // Undeclared exception!
      try { 
        emailTask0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      EmailTask emailTask0 = new EmailTask();
      EmailTask.Encoding emailTask_Encoding0 = new EmailTask.Encoding();
      emailTask_Encoding0.getValue();
      emailTask_Encoding0.indexOfValue("");
      emailTask_Encoding0.getValue();
      emailTask0.getOwningTarget();
      emailTask0.setOwningTarget((Target) null);
      emailTask0.setEncoding(emailTask_Encoding0);
      emailTask0.setFrom("");
      emailTask0.setBccList("");
      emailTask0.setMailport((-3509));
      emailTask0.setIncludefilenames(true);
  }
}
