/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:37:44 GMT 2020
 */

package org.apache.tools.ant;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PrintStream;
import java.io.PrintWriter;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.Location;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;
import org.xml.sax.helpers.LocatorImpl;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BuildException_ESTest extends BuildException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      BuildException buildException0 = new BuildException("KNYm?r)3QSlJ}ZPW?");
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      buildException0.printStackTrace(printWriter0);
      assertEquals("KNYm?r)3QSlJ}ZPW?", buildException0.getMessage());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      BuildException buildException0 = new BuildException();
      MockPrintStream mockPrintStream0 = new MockPrintStream("null");
      buildException0.printStackTrace((PrintStream) mockPrintStream0);
      assertNull(buildException0.getMessage());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      BuildException buildException0 = new BuildException("KNYm?r)3QSlJ}ZPW?");
      buildException0.printStackTrace();
      assertEquals("KNYm?r)3QSlJ}ZPW?", buildException0.getMessage());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      BuildException buildException0 = new BuildException();
      LocatorImpl locatorImpl0 = new LocatorImpl();
      Location location0 = new Location(locatorImpl0);
      BuildException buildException1 = new BuildException(buildException0, location0);
      assertFalse(buildException1.equals((Object)buildException0));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Location location0 = mock(Location.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(location0).toString();
      BuildException buildException0 = new BuildException((String) null, location0);
      BuildException buildException1 = new BuildException(buildException0);
      assertEquals("nullnull", buildException1.getMessage());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      BuildException buildException0 = new BuildException();
      String string0 = buildException0.toString();
      assertEquals("null", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      BuildException buildException0 = new BuildException();
      Location location0 = buildException0.getLocation();
      assertNotNull(location0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      BuildException buildException0 = new BuildException("tIKYV");
      Throwable throwable0 = buildException0.getCause();
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      BuildException buildException0 = new BuildException("pF^2,3YqLsOR", (Location) null);
      BuildException buildException1 = new BuildException("pF^2,3YqLsOR", buildException0, (Location) null);
      assertFalse(buildException1.equals((Object)buildException0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      BuildException buildException0 = new BuildException();
      Throwable throwable0 = buildException0.getException();
      assertNull(throwable0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Location location0 = mock(Location.class, new ViolatedAssumptionAnswer());
      BuildException buildException0 = new BuildException((String) null, location0);
      BuildException buildException1 = new BuildException("", buildException0);
      buildException0.setLocation((Location) null);
      PrintWriter printWriter0 = mock(PrintWriter.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        buildException1.printStackTrace(printWriter0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.BuildException", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      BuildException buildException0 = new BuildException("KNYm?r)3QSlJ}ZPW?");
      // Undeclared exception!
      try { 
        buildException0.printStackTrace((PrintStream) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.BuildException", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      BuildException buildException0 = new BuildException("WQc=$`[N=n8voArZ", (Location) null);
      // Undeclared exception!
      try { 
        buildException0.printStackTrace();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.BuildException", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      BuildException buildException0 = new BuildException("pF^2,3YqLsOR", (Location) null);
      BuildException buildException1 = null;
      try {
        buildException1 = new BuildException(buildException0, (Location) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.BuildException", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      BuildException buildException0 = null;
      try {
        buildException0 = new BuildException((Throwable) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.BuildException", e);
      }
  }
}
