/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 21:50:30 GMT 2020
 */

package org.apache.tools.ant;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.DirectoryScanner;
import org.apache.tools.ant.types.Resource;
import org.apache.tools.ant.types.selectors.FileSelector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DirectoryScanner_ESTest extends DirectoryScanner_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      directoryScanner0.haveSlowResults = true;
      directoryScanner0.slowScan();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "";
      stringArray0[1] = "S";
      stringArray0[2] = "6)h(X$geZ~SU";
      directoryScanner0.setExcludes(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      directoryScanner0.setBasedir("&f*U4R,'/%kx%0z%-EG");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      boolean boolean0 = DirectoryScanner.matchPatternStart(":_@", "-oIx/^b|J3d:$.6ZTq", true);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      boolean boolean0 = DirectoryScanner.matchPatternStart("", "");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      boolean boolean0 = DirectoryScanner.matchPath("2?4d'].vja", "", false);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      boolean boolean0 = DirectoryScanner.matchPath("XFcpQ;Bhi(#ao&*W[K#", "");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = DirectoryScanner.match("wwY^juCr8]?f?3^8w", "wwY^juCr8]?f?3^8w", true);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = DirectoryScanner.match("65z#uRq3?E^", "65z#uRq3?E^");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      directoryScanner0.setIncludes(stringArray0);
      boolean boolean0 = directoryScanner0.isIncluded("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "_EC_";
      stringArray0[4] = "W;";
      stringArray0[5] = " >V\"Z|^AzG";
      directoryScanner0.excludes = stringArray0;
      boolean boolean0 = directoryScanner0.isExcluded("=");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      Resource resource0 = directoryScanner0.getResource("=");
      assertNotNull(resource0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      String[] stringArray0 = new String[5];
      stringArray0[0] = ":9|L{CcZjB:U n";
      stringArray0[1] = "_GG8@]";
      stringArray0[2] = "I3^=QCp~DG";
      stringArray0[3] = ";V0MzqyG`V'u{YA";
      stringArray0[4] = "SQprl`uX`v";
      directoryScanner0.setIncludes(stringArray0);
      boolean boolean0 = directoryScanner0.couldHoldIncluded("MLdi`l!");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      FileSelector[] fileSelectorArray0 = new FileSelector[0];
      directoryScanner0.setSelectors(fileSelectorArray0);
      assertEquals(0, fileSelectorArray0.length);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      directoryScanner0.setFollowSymlinks(true);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      directoryScanner0.setCaseSensitive(true);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      directoryScanner0.setBasedir((File) null);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      boolean boolean0 = directoryScanner0.isSelected("", (File) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      boolean boolean0 = directoryScanner0.isEverythingIncluded();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      File file0 = directoryScanner0.getBasedir();
      assertNull(file0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      directoryScanner0.addDefaultExcludes();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.slowScan();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      String[] stringArray0 = new String[9];
      // Undeclared exception!
      try { 
        directoryScanner0.setIncludes(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      try { 
        directoryScanner0.setExcludes(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.setBasedir((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.scandir((File) null, "r-8rE;HgB.", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      try { 
        directoryScanner0.scan();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // No basedir set
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      // Undeclared exception!
      try { 
        DirectoryScanner.matchPatternStart((String) null, "6)h(X$geZ~SU", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.selectors.SelectorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      // Undeclared exception!
      try { 
        DirectoryScanner.matchPatternStart("", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.selectors.SelectorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      // Undeclared exception!
      try { 
        DirectoryScanner.matchPath((String) null, "*", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.selectors.SelectorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      // Undeclared exception!
      try { 
        DirectoryScanner.matchPath("", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.selectors.SelectorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      // Undeclared exception!
      try { 
        DirectoryScanner.match((String) null, (String) null, false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.selectors.SelectorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      // Undeclared exception!
      try { 
        DirectoryScanner.match("", (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.selectors.SelectorUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.isIncluded("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.isExcluded("'\"~vvF#Ym~&5");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getResource((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.util.FileUtils", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getNotIncludedFiles();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getNotIncludedDirectories();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getIncludedFiles();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getIncludedDirectories();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getExcludedFiles();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getExcludedDirectories();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getDeselectedFiles();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.getDeselectedDirectories();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      DirectoryScanner directoryScanner0 = new DirectoryScanner();
      // Undeclared exception!
      try { 
        directoryScanner0.couldHoldIncluded("NfOwp@AW<euM");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.DirectoryScanner", e);
      }
  }
}
