/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:43:30 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.sitraka;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.DirectoryScanner;
import org.apache.tools.ant.taskdefs.optional.sitraka.CovMerge;
import org.apache.tools.ant.types.FileSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CovMerge_ESTest extends CovMerge_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CovMerge covMerge0 = new CovMerge();
      File[] fileArray0 = covMerge0.getSnapshots();
      assertEquals(0, fileArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CovMerge covMerge0 = new CovMerge();
      covMerge0.setVerbose(false);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CovMerge covMerge0 = new CovMerge();
      File file0 = covMerge0.findCoverageJar();
      covMerge0.setTofile(file0);
      assertFalse(file0.isHidden());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CovMerge covMerge0 = new CovMerge();
      FileSet fileSet0 = mock(FileSet.class, new ViolatedAssumptionAnswer());
      doReturn((DirectoryScanner) null).when(fileSet0).getDirectoryScanner(any(org.apache.tools.ant.Project.class));
      covMerge0.addFileset(fileSet0);
      // Undeclared exception!
      try { 
        covMerge0.getSnapshots();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.CovMerge", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CovMerge covMerge0 = new CovMerge();
      try { 
        covMerge0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // 'tofile' attribute must be set.
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.CovMerge", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CovMerge covMerge0 = new CovMerge();
      FileSet fileSet0 = mock(FileSet.class, new ViolatedAssumptionAnswer());
      doReturn((DirectoryScanner) null).when(fileSet0).getDirectoryScanner(any(org.apache.tools.ant.Project.class));
      covMerge0.addFileset(fileSet0);
      // Undeclared exception!
      try { 
        covMerge0.createParamFile();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.CovMerge", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CovMerge covMerge0 = new CovMerge();
      try { 
        covMerge0.checkOptions();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // 'tofile' attribute must be set.
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.CovMerge", e);
      }
  }
}
