/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:36:26 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.sitraka;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.sitraka.ReportFilters;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ReportFilters_ESTest extends ReportFilters_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ReportFilters reportFilters0 = new ReportFilters();
      int int0 = reportFilters0.size();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ReportFilters reportFilters0 = new ReportFilters();
      reportFilters0.createMatchers();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ReportFilters.Include reportFilters_Include0 = new ReportFilters.Include();
      String string0 = reportFilters_Include0.toString();
      assertEquals("*.*()", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ReportFilters.Include reportFilters_Include0 = new ReportFilters.Include();
      reportFilters_Include0.setMethod("");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ReportFilters.Include reportFilters_Include0 = new ReportFilters.Include();
      String string0 = reportFilters_Include0.getAsPattern();
      assertEquals(".*\\..*\\(\\)", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ReportFilters reportFilters0 = new ReportFilters();
      reportFilters0.filters = null;
      // Undeclared exception!
      try { 
        reportFilters0.size();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.ReportFilters", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ReportFilters reportFilters0 = new ReportFilters();
      reportFilters0.addInclude((ReportFilters.Include) null);
      // Undeclared exception!
      try { 
        reportFilters0.createMatchers();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.ReportFilters", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ReportFilters.Exclude reportFilters_Exclude0 = new ReportFilters.Exclude();
      ReportFilters reportFilters0 = new ReportFilters();
      reportFilters0.filters = null;
      // Undeclared exception!
      try { 
        reportFilters0.addExclude(reportFilters_Exclude0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.ReportFilters", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ReportFilters reportFilters0 = new ReportFilters();
      ReportFilters.Include reportFilters_Include0 = new ReportFilters.Include();
      reportFilters0.addInclude(reportFilters_Include0);
      reportFilters_Include0.setClass("^M w\"[");
      // Undeclared exception!
      try { 
        reportFilters0.accept("");
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // java.util.regex.PatternSyntaxException: Unclosed character class near index 13
         // ^M w\"[\\..*\\(\\)
         //              ^
         //
         verifyException("org.apache.tools.ant.util.regexp.Jdk14RegexpMatcher", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ReportFilters reportFilters0 = new ReportFilters();
      reportFilters0.addInclude((ReportFilters.Include) null);
      // Undeclared exception!
      try { 
        reportFilters0.accept(".()");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sitraka.ReportFilters", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ReportFilters.Exclude reportFilters_Exclude0 = new ReportFilters.Exclude();
      ReportFilters reportFilters0 = new ReportFilters();
      reportFilters0.accept("(^7Px\"");
      reportFilters0.addExclude(reportFilters_Exclude0);
      // Undeclared exception!
      try { 
        reportFilters0.accept("P;:-9IFq\"GF^UrC");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0 >= 0
         //
         verifyException("java.util.Vector", e);
      }
  }
}
