/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:15:10 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.jlink;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.jlink.JlinkTask;
import org.apache.tools.ant.types.Path;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JlinkTask_ESTest extends JlinkTask_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JlinkTask jlinkTask0 = new JlinkTask();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      jlinkTask0.setOutfile(file0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JlinkTask jlinkTask0 = new JlinkTask();
      Path path0 = jlinkTask0.createAddfiles();
      jlinkTask0.setMergefiles(path0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JlinkTask jlinkTask0 = new JlinkTask();
      jlinkTask0.setCompress(false);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JlinkTask jlinkTask0 = new JlinkTask();
      Path path0 = jlinkTask0.createMergefiles();
      assertNotNull(path0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JlinkTask jlinkTask0 = new JlinkTask();
      Path path0 = jlinkTask0.createAddfiles();
      jlinkTask0.setAddfiles(path0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JlinkTask jlinkTask0 = new JlinkTask();
      try { 
        jlinkTask0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // outfile attribute is required! Please set.
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.jlink.JlinkTask", e);
      }
  }
}
