/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 21:51:35 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.jlink;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.optional.jlink.jlink;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class jlink_ESTest extends jlink_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[4];
      jlink.main(stringArray0);
      assertEquals(4, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      jlink jlink0 = new jlink();
      jlink0.setOutfile("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      jlink jlink0 = new jlink();
      jlink0.setCompression(false);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      jlink jlink0 = new jlink();
      String[] stringArray0 = new String[7];
      jlink0.addMergeFiles(stringArray0);
      assertEquals(7, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      jlink jlink0 = new jlink();
      jlink0.addMergeFile("p:Vpqg]W&ygPt%vCi");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      jlink jlink0 = new jlink();
      jlink0.addAddFiles((String[]) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      jlink jlink0 = new jlink();
      jlink0.addAddFile("N TPtH+DsC!W$MroO|");
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      // Undeclared exception!
      try { 
        jlink.main((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.jlink.jlink", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      jlink jlink0 = new jlink();
      try { 
        jlink0.link();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // name can't be null
         //
         verifyException("java.io.FilePermission", e);
      }
  }
}
