/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:58:32 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.ssh;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.jcraft.jsch.JSchException;
import org.apache.tools.ant.taskdefs.optional.ssh.SSHExec;
import org.apache.tools.ant.taskdefs.optional.ssh.SSHUserInfo;
import org.apache.tools.ant.taskdefs.optional.ssh.Scp;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SSHBase_ESTest extends SSHBase_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.setUsername("$5p([?21q[");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SSHExec sSHExec0 = new SSHExec();
      sSHExec0.setTrust(true);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SSHExec sSHExec0 = new SSHExec();
      sSHExec0.setPort(1364);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.setPassword("pq1Yox9/]4/vlv");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.setPassphrase("");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.setKnownhosts("%yo%AP;&1-P`|>mZh");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.setHost("[");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.setFailonerror(false);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.init();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Scp scp0 = new Scp();
      SSHUserInfo sSHUserInfo0 = scp0.getUserInfo();
      assertNotNull(sSHUserInfo0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SSHExec sSHExec0 = new SSHExec();
      int int0 = sSHExec0.getPort();
      assertEquals(22, int0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Scp scp0 = new Scp();
      String string0 = scp0.getHost();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SSHExec sSHExec0 = new SSHExec();
      boolean boolean0 = sSHExec0.getFailonerror();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Scp scp0 = new Scp();
      // Undeclared exception!
      try { 
        scp0.openSession();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Scp scp0 = new Scp();
      scp0.setKeyfile("");
      try { 
        scp0.openSession();
        fail("Expecting exception: JSchException");
      
      } catch(JSchException e) {
         //
         // java.io.FileNotFoundException:  (No such file or directory)
         //
         verifyException("com.jcraft.jsch.IdentityFile", e);
      }
  }
}
