/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:18:55 GMT 2020
 */

package org.apache.tools.ant.taskdefs.cvslib;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.cvslib.CVSEntry;
import org.apache.tools.ant.taskdefs.cvslib.ChangeLogParser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChangeLogParser_ESTest extends ChangeLogParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChangeLogParser changeLogParser0 = new ChangeLogParser();
      changeLogParser0.stdout("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChangeLogParser changeLogParser0 = new ChangeLogParser();
      CVSEntry[] cVSEntryArray0 = changeLogParser0.getEntrySetAsArray();
      assertEquals(0, cVSEntryArray0.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChangeLogParser changeLogParser0 = new ChangeLogParser();
      // Undeclared exception!
      try { 
        changeLogParser0.stdout((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.cvslib.ChangeLogParser", e);
      }
  }
}
