/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:08:09 GMT 2020
 */

package org.apache.tools.ant.taskdefs.cvslib;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.cvslib.CvsTagDiff;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CvsTagDiff_ESTest extends CvsTagDiff_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CvsTagDiff cvsTagDiff0 = new CvsTagDiff();
      cvsTagDiff0.setStartTag("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CvsTagDiff cvsTagDiff0 = new CvsTagDiff();
      cvsTagDiff0.setStartDate((String) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CvsTagDiff cvsTagDiff0 = new CvsTagDiff();
      cvsTagDiff0.setPackage("A{R|");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CvsTagDiff cvsTagDiff0 = new CvsTagDiff();
      cvsTagDiff0.setEndTag("A{R|");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CvsTagDiff cvsTagDiff0 = new CvsTagDiff();
      cvsTagDiff0.setEndDate("");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CvsTagDiff cvsTagDiff0 = new CvsTagDiff();
      cvsTagDiff0.setDestFile((File) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CvsTagDiff cvsTagDiff0 = new CvsTagDiff();
      try { 
        cvsTagDiff0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Package/module must be set.
         //
         verifyException("org.apache.tools.ant.taskdefs.cvslib.CvsTagDiff", e);
      }
  }
}
