/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:11:02 GMT 2020
 */

package org.apache.tools.ant.taskdefs.cvslib;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.tools.ant.taskdefs.cvslib.CvsTagEntry;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CvsTagEntry_ESTest extends CvsTagEntry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CvsTagEntry cvsTagEntry0 = new CvsTagEntry("2Y,", "2Y,");
      String string0 = cvsTagEntry0.toString();
      assertEquals("2Y, is new; current revision is 2Y,", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CvsTagEntry cvsTagEntry0 = new CvsTagEntry("2Y,", "2Y,");
      String string0 = cvsTagEntry0.getRevision();
      assertEquals("2Y,", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CvsTagEntry cvsTagEntry0 = new CvsTagEntry("2Y,", "2Y,");
      String string0 = cvsTagEntry0.getPreviousRevision();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CvsTagEntry cvsTagEntry0 = new CvsTagEntry("J0W?v-t~", "J0W?v-t~", "J0W?v-t~");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CvsTagEntry cvsTagEntry0 = new CvsTagEntry("2Y,", "2Y,");
      String string0 = cvsTagEntry0.getFile();
      assertEquals("2Y,", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CvsTagEntry cvsTagEntry0 = new CvsTagEntry((String) null);
  }
}
