/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:56:44 GMT 2020
 */

package org.apache.tools.ant.taskdefs.cvslib;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.PipedInputStream;
import org.apache.tools.ant.taskdefs.cvslib.ChangeLogParser;
import org.apache.tools.ant.taskdefs.cvslib.RedirectingStreamHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RedirectingStreamHandler_ESTest extends RedirectingStreamHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChangeLogParser changeLogParser0 = new ChangeLogParser();
      RedirectingStreamHandler redirectingStreamHandler0 = new RedirectingStreamHandler(changeLogParser0);
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      redirectingStreamHandler0.setProcessOutputStream(pipedInputStream0);
      redirectingStreamHandler0.setProcessErrorStream(pipedInputStream0);
      redirectingStreamHandler0.stop();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChangeLogParser changeLogParser0 = new ChangeLogParser();
      RedirectingStreamHandler redirectingStreamHandler0 = new RedirectingStreamHandler(changeLogParser0);
      String string0 = redirectingStreamHandler0.getErrors();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChangeLogParser changeLogParser0 = new ChangeLogParser();
      RedirectingStreamHandler redirectingStreamHandler0 = new RedirectingStreamHandler(changeLogParser0);
      // Undeclared exception!
      try { 
        redirectingStreamHandler0.stop();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.PumpStreamHandler", e);
      }
  }
}
