/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:06:30 GMT 2020
 */

package org.apache.tools.ant.taskdefs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.BUnzip2;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BUnzip2_ESTest extends BUnzip2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BUnzip2 bUnzip2_0 = new BUnzip2();
      String string0 = bUnzip2_0.getDefaultExtension();
      assertEquals(".bz2", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BUnzip2 bUnzip2_0 = new BUnzip2();
      // Undeclared exception!
      try { 
        bUnzip2_0.extract();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.BUnzip2", e);
      }
  }
}
