/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:00:40 GMT 2020
 */

package org.apache.tools.ant.taskdefs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.LoadFile;
import org.apache.tools.ant.types.FilterChain;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LoadFile_ESTest extends LoadFile_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LoadFile loadFile0 = new LoadFile();
      loadFile0.setFailonerror(false);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LoadFile loadFile0 = new LoadFile();
      loadFile0.setEncoding("5SD-NBQ");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LoadFile loadFile0 = new LoadFile();
      FilterChain filterChain0 = new FilterChain();
      loadFile0.addFilterChain(filterChain0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LoadFile loadFile0 = new LoadFile();
      try { 
        loadFile0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // source file not defined
         //
         verifyException("org.apache.tools.ant.taskdefs.LoadFile", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LoadFile loadFile0 = new LoadFile();
      loadFile0.setProperty("");
      MockFile mockFile0 = new MockFile("", "");
      loadFile0.setSrcFile(mockFile0);
      // Undeclared exception!
      try { 
        loadFile0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }
}
