/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:11:49 GMT 2020
 */

package org.apache.tools.ant.taskdefs;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.WhichResource;
import org.apache.tools.ant.types.Path;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WhichResource_ESTest extends WhichResource_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      WhichResource whichResource0 = new WhichResource();
      whichResource0.setResource((String) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      WhichResource whichResource0 = new WhichResource();
      Path path0 = whichResource0.createClasspath();
      whichResource0.setClasspath(path0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      WhichResource whichResource0 = new WhichResource();
      try { 
        whichResource0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // One of classname or resource must be specified
         //
         verifyException("org.apache.tools.ant.taskdefs.WhichResource", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      WhichResource whichResource0 = new WhichResource();
      whichResource0.setClass("");
      whichResource0.setProperty("*q=[&7<~4%o%TQ");
      // Undeclared exception!
      try { 
        whichResource0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.WhichResource", e);
      }
  }
}
