/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:48:16 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.perforce;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.optional.perforce.P4Label;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class P4Label_ESTest extends P4Label_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      P4Label p4Label0 = new P4Label();
      p4Label0.setName("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      P4Label p4Label0 = new P4Label();
      p4Label0.setLock("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      P4Label p4Label0 = new P4Label();
      p4Label0.setDesc("kJi?;syU4(>y'U");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      P4Label p4Label0 = new P4Label();
      // Undeclared exception!
      try { 
        p4Label0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }
}
