/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:23:01 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.net;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.optional.net.SetProxy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SetProxy_ESTest extends SetProxy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.execute();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.applyWebProxySettings();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.setSocksProxyPort(746);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.setProxyUser((String) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.setProxyPort(746);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.setProxyPassword("foH?GrT3{P[7-.t");
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.setNonProxyHosts("");
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      boolean boolean0 = setProxy0.legacyResetProxySettingsCall(true);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.setProxyHost("");
      // Undeclared exception!
      try { 
        setProxy0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      SetProxy setProxy0 = new SetProxy();
      setProxy0.setSocksProxyHost("");
      // Undeclared exception!
      try { 
        setProxy0.applyWebProxySettings();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }
}
