/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:42:45 GMT 2020
 */

package org.apache.tools.ant.types;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.types.EnumeratedAttributeTest;
import org.apache.tools.ant.types.Mapper;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EnumeratedAttribute_ESTest extends EnumeratedAttribute_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      EnumeratedAttributeTest.TestNormal enumeratedAttributeTest_TestNormal0 = new EnumeratedAttributeTest.TestNormal();
      String string0 = enumeratedAttributeTest_TestNormal0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mapper.MapperType mapper_MapperType0 = new Mapper.MapperType();
      int int0 = mapper_MapperType0.indexOfValue("");
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EnumeratedAttributeTest.TestNull enumeratedAttributeTest_TestNull0 = new EnumeratedAttributeTest.TestNull();
      String[] stringArray0 = enumeratedAttributeTest_TestNull0.getValues();
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EnumeratedAttributeTest.TestNormal enumeratedAttributeTest_TestNormal0 = new EnumeratedAttributeTest.TestNormal();
      String string0 = enumeratedAttributeTest_TestNormal0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EnumeratedAttributeTest.TestNormal enumeratedAttributeTest_TestNormal0 = new EnumeratedAttributeTest.TestNormal();
      int int0 = enumeratedAttributeTest_TestNormal0.getIndex();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      EnumeratedAttributeTest.TestNormal enumeratedAttributeTest_TestNormal0 = new EnumeratedAttributeTest.TestNormal();
      boolean boolean0 = enumeratedAttributeTest_TestNormal0.containsValue("?");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Mapper.MapperType mapper_MapperType0 = new Mapper.MapperType();
      try { 
        mapper_MapperType0.setValue((String) null);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // null is not a legal value for this attribute
         //
         verifyException("org.apache.tools.ant.types.EnumeratedAttribute", e);
      }
  }
}
