/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:10:04 GMT 2020
 */

package org.apache.tools.ant.types;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.types.FileSet;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FileSet_ESTest extends FileSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileSet fileSet0 = new FileSet();
      FileSet fileSet1 = new FileSet(fileSet0);
      assertFalse(fileSet1.equals((Object)fileSet0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FileSet fileSet0 = new FileSet();
      Object object0 = fileSet0.clone();
      assertNotSame(fileSet0, object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FileSet fileSet0 = null;
      try {
        fileSet0 = new FileSet((FileSet) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.AbstractFileSet", e);
      }
  }
}
