/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:08:37 GMT 2020
 */

package org.apache.tools.ant.types;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.Project;
import org.apache.tools.ant.types.RegularExpression;
import org.apache.tools.ant.util.regexp.Regexp;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RegularExpression_ESTest extends RegularExpression_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegularExpression regularExpression0 = new RegularExpression();
      regularExpression0.setPattern("K^*NF");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RegularExpression regularExpression0 = new RegularExpression();
      Project project0 = mock(Project.class, new ViolatedAssumptionAnswer());
      Regexp regexp0 = regularExpression0.getRegexp(project0);
      assertNotNull(regexp0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RegularExpression regularExpression0 = new RegularExpression();
      String string0 = regularExpression0.getPattern((Project) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RegularExpression regularExpression0 = new RegularExpression();
      Project project0 = mock(Project.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        regularExpression0.getRef(project0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.RegularExpression", e);
      }
  }
}
