/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:53:45 GMT 2020
 */

package org.apache.tools.ant.types;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.URL;
import org.apache.tools.ant.types.ResourceLocation;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ResourceLocation_ESTest extends ResourceLocation_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ResourceLocation resourceLocation0 = new ResourceLocation();
      resourceLocation0.setPublicId("?zQ: )MO");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ResourceLocation resourceLocation0 = new ResourceLocation();
      resourceLocation0.setLocation("q_{wia+o[ o");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ResourceLocation resourceLocation0 = new ResourceLocation();
      resourceLocation0.setBase((URL) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ResourceLocation resourceLocation0 = new ResourceLocation();
      String string0 = resourceLocation0.getPublicId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ResourceLocation resourceLocation0 = new ResourceLocation();
      String string0 = resourceLocation0.getLocation();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ResourceLocation resourceLocation0 = new ResourceLocation();
      URL uRL0 = resourceLocation0.getBase();
      assertNull(uRL0);
  }
}
