/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:37:50 GMT 2020
 */

package org.apache.tools.ant.filters;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.apache.tools.ant.filters.EscapeUnicode;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class EscapeUnicode_ESTest extends EscapeUnicode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringReader stringReader0 = new StringReader("3Yw uIJAm");
      EscapeUnicode escapeUnicode0 = new EscapeUnicode(stringReader0);
      int int0 = escapeUnicode0.read();
      assertEquals(51, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      EscapeUnicode escapeUnicode0 = new EscapeUnicode();
      Reader reader0 = escapeUnicode0.chain(escapeUnicode0);
      assertFalse(reader0.equals((Object)escapeUnicode0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      EscapeUnicode escapeUnicode0 = new EscapeUnicode();
      try { 
        escapeUnicode0.read();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream closed
         //
         verifyException("java.io.StringReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EscapeUnicode escapeUnicode0 = new EscapeUnicode();
      // Undeclared exception!
      try { 
        escapeUnicode0.chain((Reader) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      EscapeUnicode escapeUnicode0 = null;
      try {
        escapeUnicode0 = new EscapeUnicode((Reader) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }
}
