/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:34:54 GMT 2020
 */

package org.apache.tools.ant.filters;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import org.apache.tools.ant.filters.TabsToSpaces;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TabsToSpaces_ESTest extends TabsToSpaces_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringReader stringReader0 = new StringReader("|6");
      TabsToSpaces tabsToSpaces0 = new TabsToSpaces(stringReader0);
      int int0 = tabsToSpaces0.read();
      assertEquals(124, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      TabsToSpaces tabsToSpaces0 = new TabsToSpaces(stringReader0);
      Reader reader0 = tabsToSpaces0.chain(stringReader0);
      assertNotSame(tabsToSpaces0, reader0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringReader stringReader0 = new StringReader("");
      TabsToSpaces tabsToSpaces0 = new TabsToSpaces(stringReader0);
      tabsToSpaces0.setTablength(0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TabsToSpaces tabsToSpaces0 = new TabsToSpaces();
      try { 
        tabsToSpaces0.read();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Stream closed
         //
         verifyException("java.io.StringReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      TabsToSpaces tabsToSpaces0 = new TabsToSpaces();
      // Undeclared exception!
      try { 
        tabsToSpaces0.chain((Reader) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      TabsToSpaces tabsToSpaces0 = null;
      try {
        tabsToSpaces0 = new TabsToSpaces((Reader) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.Reader", e);
      }
  }
}
