/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 21:53:49 GMT 2020
 */

package org.apache.tools.ant.taskdefs.condition;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.condition.Os;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Os_ESTest extends Os_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Os os0 = new Os();
      os0.setVersion("B!VC'E1T2-r#iwY4%q");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Os os0 = new Os();
      os0.setName("x>;D");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Os os0 = new Os();
      os0.setFamily("");
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Os os0 = new Os();
      os0.setArch(" MP");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      boolean boolean0 = Os.isOs((String) null, "rm4uQF7", "", (String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      boolean boolean0 = Os.isFamily((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Os os0 = new Os();
      boolean boolean0 = os0.eval();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      boolean boolean0 = Os.isVersion("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      boolean boolean0 = Os.isName("B!VC'E1T2-r#iwY4%q");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      boolean boolean0 = Os.isArch("B!VC'E1T2-r#iwY4%q");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Os os0 = new Os("Kol#vw/CHw<{5");
      // Undeclared exception!
      try { 
        os0.setVersion((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Os os0 = new Os();
      // Undeclared exception!
      try { 
        os0.setName((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Os os0 = new Os("");
      // Undeclared exception!
      try { 
        os0.setFamily((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Os os0 = new Os();
      // Undeclared exception!
      try { 
        os0.setArch((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        Os.isOs("'TWGAslt5f-f", "", "'TWGAslt5f-f", (String) null);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Don't know how to detect os family \"'TWGAslt5f-f\"
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        Os.isFamily("");
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Don't know how to detect os family \"\"
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Os os0 = new Os("z.UE3N0IiOUZSJkZ");
      try { 
        os0.eval();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Don't know how to detect os family \"z.ue3n0iiouzsjkz\"
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Os os0 = null;
      try {
        os0 = new Os((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.condition.Os", e);
      }
  }
}
