/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:09:34 GMT 2020
 */

package org.apache.tools.ant.types.optional.image;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.tools.ant.types.optional.image.Ellipse;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BasicShape_ESTest extends BasicShape_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ellipse ellipse0 = new Ellipse();
      ellipse0.setStrokewidth(0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Ellipse ellipse0 = new Ellipse();
      ellipse0.setStroke("!ar\"+}QHtqk\"_");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Ellipse ellipse0 = new Ellipse();
      ellipse0.setFill("eVmKuD2irj/O!");
  }
}
