/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:37:55 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.clearcase;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.clearcase.CCMklabel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CCMklabel_ESTest extends CCMklabel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      cCMklabel0.setVersion("");
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      cCMklabel0.setVOB("");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      cCMklabel0.setReplace(true);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      cCMklabel0.setRecurse(true);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      cCMklabel0.setCommentFile("");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      cCMklabel0.setComment("");
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      String string0 = cCMklabel0.getVersion();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      String string0 = cCMklabel0.getVOB();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      String string0 = cCMklabel0.getTypeName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      boolean boolean0 = cCMklabel0.getReplace();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      boolean boolean0 = cCMklabel0.getRecurse();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      String string0 = cCMklabel0.getCommentFile();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      String string0 = cCMklabel0.getComment();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      try { 
        cCMklabel0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Required attribute TypeName not specified
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.clearcase.CCMklabel", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CCMklabel cCMklabel0 = new CCMklabel();
      cCMklabel0.setTypeName("");
      // Undeclared exception!
      try { 
        cCMklabel0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.clearcase.CCMklabel", e);
      }
  }
}
