/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:37:16 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.clearcase;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.optional.clearcase.CCUnlock;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CCUnlock_ESTest extends CCUnlock_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CCUnlock cCUnlock0 = new CCUnlock();
      cCUnlock0.setPname("2");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CCUnlock cCUnlock0 = new CCUnlock();
      cCUnlock0.setObjselect("[hjJ)");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CCUnlock cCUnlock0 = new CCUnlock();
      cCUnlock0.setComment((String) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CCUnlock cCUnlock0 = new CCUnlock();
      String string0 = cCUnlock0.getPname();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CCUnlock cCUnlock0 = new CCUnlock();
      String string0 = cCUnlock0.getObjselect();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      CCUnlock cCUnlock0 = new CCUnlock();
      String string0 = cCUnlock0.getComment();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CCUnlock cCUnlock0 = new CCUnlock();
      // Undeclared exception!
      try { 
        cCUnlock0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.clearcase.CCUnlock", e);
      }
  }
}
