/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:47:50 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.j2ee;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.taskdefs.optional.j2ee.GenericHotDeploymentTool;
import org.apache.tools.ant.taskdefs.optional.j2ee.JonasHotDeploymentTool;
import org.apache.tools.ant.taskdefs.optional.j2ee.ServerDeploy;
import org.apache.tools.ant.taskdefs.optional.j2ee.WebLogicHotDeploymentTool;
import org.apache.tools.ant.types.Path;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AbstractHotDeploymentTool_ESTest extends AbstractHotDeploymentTool_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      Path path0 = webLogicHotDeploymentTool0.getClasspath();
      assertNull(path0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      webLogicHotDeploymentTool0.setUserName("zCRm6rQZ");
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      webLogicHotDeploymentTool0.setTask((ServerDeploy) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      webLogicHotDeploymentTool0.setServer("");
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      webLogicHotDeploymentTool0.setPassword("");
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      webLogicHotDeploymentTool0.setClasspath((Path) null);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      String string0 = webLogicHotDeploymentTool0.getUserName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      ServerDeploy serverDeploy0 = webLogicHotDeploymentTool0.getTask();
      assertNull(serverDeploy0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      String string0 = webLogicHotDeploymentTool0.getServer();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      String string0 = webLogicHotDeploymentTool0.getPassword();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WebLogicHotDeploymentTool webLogicHotDeploymentTool0 = new WebLogicHotDeploymentTool();
      // Undeclared exception!
      try { 
        webLogicHotDeploymentTool0.validateAttributes();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.j2ee.AbstractHotDeploymentTool", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      JonasHotDeploymentTool jonasHotDeploymentTool0 = new JonasHotDeploymentTool();
      // Undeclared exception!
      try { 
        jonasHotDeploymentTool0.getClasspath();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.j2ee.JonasHotDeploymentTool", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      JonasHotDeploymentTool jonasHotDeploymentTool0 = new JonasHotDeploymentTool();
      // Undeclared exception!
      try { 
        jonasHotDeploymentTool0.deploy();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.j2ee.GenericHotDeploymentTool", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GenericHotDeploymentTool genericHotDeploymentTool0 = new GenericHotDeploymentTool();
      // Undeclared exception!
      try { 
        genericHotDeploymentTool0.createClasspath();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.j2ee.AbstractHotDeploymentTool", e);
      }
  }
}
