/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 21:53:34 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.IContract;
import org.apache.tools.ant.types.Path;
import org.apache.tools.ant.types.Reference;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class IContract_ESTest extends IContract_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(file0).exists();
      iContract0.setControlfile(file0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      IContract iContract0 = new IContract();
      Path path0 = iContract0.createClasspath();
      iContract0.setClasspath(path0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setVerbosity((String) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setUpdateicontrol(true);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      iContract0.setTargets(file0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      iContract0.setSrcdir(file0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setRepositorydir((File) null);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      iContract0.setRepbuilddir(file0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setQuiet(false);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setPre(true);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setPost(false);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setInvariant(true);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      iContract0.setInstrumentdir(file0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      IContract iContract0 = new IContract();
      iContract0.setFailthrowable("xy*b`<");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      iContract0.setClassdir(file0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      iContract0.setBuilddir(file0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      IContract iContract0 = new IContract();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(file0).exists();
      doReturn((String) null).when(file0).getAbsolutePath();
      // Undeclared exception!
      try { 
        iContract0.setControlfile(file0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      IContract iContract0 = new IContract();
      Reference reference0 = mock(Reference.class, new ViolatedAssumptionAnswer());
      iContract0.setClasspathRef(reference0);
      Reference reference1 = mock(Reference.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        iContract0.setClasspathRef(reference1);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // You must not specify more than one attribute when using refid
         //
         verifyException("org.apache.tools.ant.types.DataType", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      IContract iContract0 = new IContract();
      Path path0 = iContract0.createClasspath();
      Reference reference0 = mock(Reference.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(reference0).getRefId();
      doReturn((Object) null, (Object) null).when(reference0).getReferencedObject(any(org.apache.tools.ant.Project.class));
      iContract0.setClasspathRef(reference0);
      // Undeclared exception!
      try { 
        iContract0.setClasspath(path0);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // null doesn't denote a path null
         //
         verifyException("org.apache.tools.ant.types.Path", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      IContract iContract0 = new IContract();
      try { 
        iContract0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // srcdir attribute must be set!
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.IContract", e);
      }
  }
}
