/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:46:16 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.Native2Ascii;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Native2Ascii_ESTest extends Native2Ascii_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Native2Ascii native2Ascii0 = new Native2Ascii();
      native2Ascii0.setReverse(false);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Native2Ascii native2Ascii0 = new Native2Ascii();
      native2Ascii0.setExt("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Native2Ascii native2Ascii0 = new Native2Ascii();
      native2Ascii0.setEncoding("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Native2Ascii native2Ascii0 = new Native2Ascii();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      native2Ascii0.setDest(file0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Native2Ascii native2Ascii0 = new Native2Ascii();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      native2Ascii0.setSrc(file0);
      try { 
        native2Ascii0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // The dest attribute must be set.
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.Native2Ascii", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Native2Ascii native2Ascii0 = new Native2Ascii();
      // Undeclared exception!
      try { 
        native2Ascii0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.Native2Ascii", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Native2Ascii native2Ascii0 = new Native2Ascii();
      native2Ascii0.createMapper();
      try { 
        native2Ascii0.createMapper();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Cannot define more than one mapper
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.Native2Ascii", e);
      }
  }
}
