/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:56:23 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.RenameExtensions;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RenameExtensions_ESTest extends RenameExtensions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RenameExtensions renameExtensions0 = new RenameExtensions();
      renameExtensions0.setToExtension("wlQ]+`W(fNj^+P<");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RenameExtensions renameExtensions0 = new RenameExtensions();
      renameExtensions0.setReplace(false);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RenameExtensions renameExtensions0 = new RenameExtensions();
      renameExtensions0.setFromExtension("19!{RK");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RenameExtensions renameExtensions0 = new RenameExtensions();
      try { 
        renameExtensions0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // srcDir, fromExtension and toExtension attributes must be set!
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.RenameExtensions", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RenameExtensions renameExtensions0 = new RenameExtensions();
      File file0 = mock(File.class, new ViolatedAssumptionAnswer());
      renameExtensions0.setSrcDir(file0);
      // Undeclared exception!
      try { 
        renameExtensions0.execute();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.Task", e);
      }
  }
}
