/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:09:34 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.extension;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.extension.ExtensionAdapter;
import org.apache.tools.ant.taskdefs.optional.extension.JarLibResolveTask;
import org.apache.tools.ant.taskdefs.optional.extension.resolvers.AntResolver;
import org.apache.tools.ant.taskdefs.optional.extension.resolvers.LocationResolver;
import org.apache.tools.ant.taskdefs.optional.extension.resolvers.URLResolver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class JarLibResolveTask_ESTest extends JarLibResolveTask_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      jarLibResolveTask0.setProperty("%PlL+rnp)");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      jarLibResolveTask0.setFailOnError(true);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      jarLibResolveTask0.setCheckExtension(true);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      URLResolver uRLResolver0 = mock(URLResolver.class, new ViolatedAssumptionAnswer());
      jarLibResolveTask0.addConfiguredUrl(uRLResolver0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      jarLibResolveTask0.addConfiguredLocation((LocationResolver) null);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      AntResolver antResolver0 = mock(AntResolver.class, new ViolatedAssumptionAnswer());
      jarLibResolveTask0.addConfiguredAnt(antResolver0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      try { 
        jarLibResolveTask0.execute();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Property attribute must be specified.
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.extension.JarLibResolveTask", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      ExtensionAdapter extensionAdapter0 = mock(ExtensionAdapter.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        jarLibResolveTask0.addConfiguredExtension(extensionAdapter0);
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // Extension is missing name.
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.extension.ExtensionAdapter", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      JarLibResolveTask jarLibResolveTask0 = new JarLibResolveTask();
      // Undeclared exception!
      try { 
        jarLibResolveTask0.addConfiguredExtension((ExtensionAdapter) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.extension.JarLibResolveTask", e);
      }
  }
}
