/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:29:30 GMT 2020
 */

package org.apache.tools.ant.types.optional;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.Project;
import org.apache.tools.ant.types.optional.ScriptFilter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ScriptFilter_ESTest extends ScriptFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      scriptFilter0.setToken((String) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      Project project0 = mock(Project.class, new ViolatedAssumptionAnswer());
      scriptFilter0.setProject(project0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      String string0 = scriptFilter0.getToken();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      scriptFilter0.addText((String) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      // Undeclared exception!
      try { 
        scriptFilter0.setSrc("&:0Zuk");
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // file &:0Zuk not found.
         //
         verifyException("org.apache.tools.ant.types.optional.ScriptFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      // Undeclared exception!
      try { 
        scriptFilter0.setSrc((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      // Undeclared exception!
      try { 
        scriptFilter0.filter("Pw");
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // scriptfilter: language is not defined
         //
         verifyException("org.apache.tools.ant.types.optional.ScriptFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ScriptFilter scriptFilter0 = new ScriptFilter();
      scriptFilter0.setLanguage("{O`tDx5");
      // Undeclared exception!
      try { 
        scriptFilter0.filter("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.types.optional.ScriptFilter", e);
      }
  }
}
