/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:24:10 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.sos;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.tools.ant.BuildException;
import org.apache.tools.ant.taskdefs.optional.sos.SOSLabel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SOSLabel_ESTest extends SOSLabel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SOSLabel sOSLabel0 = new SOSLabel();
      sOSLabel0.setVersion("xw7hNh)8DW{lB+#<");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SOSLabel sOSLabel0 = new SOSLabel();
      sOSLabel0.setLabel("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SOSLabel sOSLabel0 = new SOSLabel();
      sOSLabel0.setComment("soscmd");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SOSLabel sOSLabel0 = new SOSLabel();
      // Undeclared exception!
      try { 
        sOSLabel0.buildCmdLine();
        fail("Expecting exception: BuildException");
      
      } catch(BuildException e) {
         //
         // sosserverpath attribute must be set!
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.sos.SOS", e);
      }
  }
}
