/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:26:12 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.depend.constantpool;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataInputStream;
import org.apache.tools.ant.taskdefs.optional.depend.constantpool.ConstantPool;
import org.apache.tools.ant.taskdefs.optional.depend.constantpool.ConstantPoolEntry;
import org.apache.tools.ant.taskdefs.optional.depend.constantpool.MethodRefCPInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MethodRefCPInfo_ESTest extends MethodRefCPInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MethodRefCPInfo methodRefCPInfo0 = new MethodRefCPInfo();
      String string0 = methodRefCPInfo0.toString();
      assertEquals("Method : Class index = 0, name and type index = 0", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MethodRefCPInfo methodRefCPInfo0 = new MethodRefCPInfo();
      String string0 = methodRefCPInfo0.getMethodType();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MethodRefCPInfo methodRefCPInfo0 = new MethodRefCPInfo();
      String string0 = methodRefCPInfo0.getMethodName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MethodRefCPInfo methodRefCPInfo0 = new MethodRefCPInfo();
      String string0 = methodRefCPInfo0.getMethodClassName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MethodRefCPInfo methodRefCPInfo0 = new MethodRefCPInfo();
      ConstantPool constantPool0 = mock(ConstantPool.class, new ViolatedAssumptionAnswer());
      doReturn((ConstantPoolEntry) null).when(constantPool0).getEntry(anyInt());
      // Undeclared exception!
      try { 
        methodRefCPInfo0.resolve(constantPool0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.depend.constantpool.MethodRefCPInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      MethodRefCPInfo methodRefCPInfo0 = new MethodRefCPInfo();
      ConstantPool constantPool0 = mock(ConstantPool.class, new ViolatedAssumptionAnswer());
      doReturn(methodRefCPInfo0).when(constantPool0).getEntry(anyInt());
      // Undeclared exception!
      try { 
        methodRefCPInfo0.resolve(constantPool0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.tools.ant.taskdefs.optional.depend.constantpool.MethodRefCPInfo cannot be cast to org.apache.tools.ant.taskdefs.optional.depend.constantpool.ClassCPInfo
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.depend.constantpool.MethodRefCPInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      MethodRefCPInfo methodRefCPInfo0 = new MethodRefCPInfo();
      DataInputStream dataInputStream0 = mock(DataInputStream.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        methodRefCPInfo0.read(dataInputStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.DataInputStream", e);
      }
  }
}
