/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:37:01 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.depend.constantpool;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataInputStream;
import org.apache.tools.ant.taskdefs.optional.depend.constantpool.ConstantPool;
import org.apache.tools.ant.taskdefs.optional.depend.constantpool.ConstantPoolEntry;
import org.apache.tools.ant.taskdefs.optional.depend.constantpool.StringCPInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StringCPInfo_ESTest extends StringCPInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StringCPInfo stringCPInfo0 = new StringCPInfo();
      String string0 = stringCPInfo0.toString();
      assertEquals("String Constant Pool Entry for null[0]", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StringCPInfo stringCPInfo0 = new StringCPInfo();
      ConstantPool constantPool0 = mock(ConstantPool.class, new ViolatedAssumptionAnswer());
      doReturn((ConstantPoolEntry) null).when(constantPool0).getEntry(anyInt());
      // Undeclared exception!
      try { 
        stringCPInfo0.resolve(constantPool0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.depend.constantpool.StringCPInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StringCPInfo stringCPInfo0 = new StringCPInfo();
      ConstantPool constantPool0 = mock(ConstantPool.class, new ViolatedAssumptionAnswer());
      doReturn(stringCPInfo0).when(constantPool0).getEntry(anyInt());
      // Undeclared exception!
      try { 
        stringCPInfo0.resolve(constantPool0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // org.apache.tools.ant.taskdefs.optional.depend.constantpool.StringCPInfo cannot be cast to org.apache.tools.ant.taskdefs.optional.depend.constantpool.Utf8CPInfo
         //
         verifyException("org.apache.tools.ant.taskdefs.optional.depend.constantpool.StringCPInfo", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StringCPInfo stringCPInfo0 = new StringCPInfo();
      DataInputStream dataInputStream0 = mock(DataInputStream.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        stringCPInfo0.read(dataInputStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.DataInputStream", e);
      }
  }
}
