/*
 * This file was automatically generated by EvoSuite
 * Sun Jan 05 22:05:30 GMT 2020
 */

package org.apache.tools.ant.taskdefs.optional.depend.constantpool;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.DataInputStream;
import org.apache.tools.ant.taskdefs.optional.depend.constantpool.Utf8CPInfo;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Utf8CPInfo_ESTest extends Utf8CPInfo_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Utf8CPInfo utf8CPInfo0 = new Utf8CPInfo();
      String string0 = utf8CPInfo0.toString();
      assertEquals("UTF8 Value = null", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Utf8CPInfo utf8CPInfo0 = new Utf8CPInfo();
      String string0 = utf8CPInfo0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Utf8CPInfo utf8CPInfo0 = new Utf8CPInfo();
      DataInputStream dataInputStream0 = mock(DataInputStream.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        utf8CPInfo0.read(dataInputStream0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.DataInputStream", e);
      }
  }
}
